name: Test requirements on linux, mac and windows

on: [push, workflow_dispatch]

jobs:
  test-import:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.13"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Create requirements directory
        run: mkdir -p requirements
        shell: bash
        if: runner.os != 'Windows'

      - name: Create requirements directory on Windows
        run: New-Item -ItemType Directory -Force -Path requirements
        shell: powershell
        if: runner.os == 'Windows'

      - name: Move files to requirements directory (Linux/macOS)
        shell: bash
        run: |
          shopt -s extglob
          mv !(requirements) requirements/
        if: runner.os != 'Windows'

      - name: Move files to requirements directory (Windows)
        shell: powershell
        run: |
          Get-ChildItem -Exclude requirements | ForEach-Object { Move-Item $_ -Destination requirements }
        if: runner.os == 'Windows'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create sample requirements.txt (Linux/macOS)
        shell: bash
        run: |
          cat <<EOF > requirements.txt
          # Custom content for requirements.txt
          numpy
          requests==2.26.0
          EOF
        if: runner.os != 'Windows'

      - name: Create sample requirements.txt (Windows)
        shell: powershell
        run: |
          @"
          # Custom content for requirements.txt
          numpy
          requests==2.26.0
          "@ | Out-File -Encoding UTF8 requirements.txt
        if: runner.os == 'Windows'

      - name: Test requirements
        run: python -c "from requirements import requirements; import numpy; import requests; assert numpy.array(); assert requests.__version__ == '2.26.0'"
  
